# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/openapi.yaml:
  info-license:
    - '#/info'
  operation-operationId:
    - '#/paths/~1api~1v1~1takeorder/post/operationId'
    - '#/paths/~1api~1v1~1orders/get/operationId'
    - '#/paths/~1api~1v1~1accountwithdrawed/get/operationId'
    - '#/paths/~1api~1v1~1order/get/operationId'
    - '#/paths/~1api~1v1~1accountorders/get/operationId'
    - '#/paths/~1api~1v1~1accountwithdraws/get/operationId'
    - '#/paths/~1api~1v1~1withdrawall/post/operationId'
  operation-4xx-response:
    - '#/paths/~1api~1v1~1takeorder/post/responses'
    - '#/paths/~1api~1v1~1orders/get/responses'
    - '#/paths/~1api~1v1~1accountwithdrawed/get/responses'
    - '#/paths/~1api~1v1~1order/get/responses'
    - '#/paths/~1api~1v1~1accountorders/get/responses'
    - '#/paths/~1api~1v1~1accountwithdraws/get/responses'
    - '#/paths/~1api~1v1~1withdrawall/post/responses'
